export {default as Home} from './Home'
export {default as ResultImage} from './ResultImage'
export {default as NewsResult} from './NewsResult'
export {default as Result} from './Result'
export {default as Footer} from './Footer'